/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 6/11/2013, 08:01:40 PM
 */
package sumaceroestrategiaaleatoria;

/**
 *
 * @author osfprieto
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        buttonCalculateB = new javax.swing.JButton();
        buttonCalculateA = new javax.swing.JButton();
        spinnerQuantity = new javax.swing.JSpinner();
        spinnerQuantity.setValue(2);
        labelQuantity = new javax.swing.JLabel();
        updateDataTableButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.getTableHeader().setReorderingAllowed(false);
        dataTable.setModel(new MyJTableModel());
        scrollPane.setViewportView(dataTable);

        buttonCalculateB.setText("Calculate B");

        buttonCalculateA.setText("Calculate A");

        labelQuantity.setText("Strategies");
        labelQuantity.setToolTipText("The number of strategies to define for the players");

        updateDataTableButton.setText("Update");
        updateDataTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCalculateB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCalculateA)
                    .addComponent(spinnerQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(labelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(updateDataTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(labelQuantity)
                .addGap(18, 18, 18)
                .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(updateDataTableButton)
                .addGap(18, 18, 18)
                .addComponent(buttonCalculateA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCalculateB)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void updateDataTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataTableButtonActionPerformed
    updateDataTable();
}//GEN-LAST:event_updateDataTableButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void updateDataTable(){
        int n = ((Integer)spinnerQuantity.getValue()).intValue();
    
        System.out.print(((MyJTableModel)dataTable.getModel()).getN()+"->");
        
        ((MyJTableModel)dataTable.getModel()).setN(n);
        dataTable.setModel(dataTable.getModel());
        
        System.out.println(((MyJTableModel)dataTable.getModel()).getN());
        
        dataTable.repaint();
        
        spinnerQuantity.setValue(Math.max(n, 2));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculateA;
    private javax.swing.JButton buttonCalculateB;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JButton updateDataTableButton;
    // End of variables declaration//GEN-END:variables
}
